#!/usr/bin/env python3
"""Generate per-entity pages at docs/entities/<termCode>.md + entities/index.md.

Projection of datasets/*.json truth — no facts are invented. Idempotent:
every run rebuilds the managed docs/entities/ directory from JSON, so stale
pages disappear automatically when entities are removed.

Scope: entity datasets = ingredients, aroma, materials, techniques, forms,
comparisons (216 records, 13 shared termCodes merge into one page each).
terminology.json keeps its existing anchor index in docs/terminology.md.

Each entity page carries:
  - stable URL:  https://data.incenseherbs.com/entities/<termCode>/
  - entity-level JSON-LD (DefinedTerm) with @id anchored to the page
  - attributes (per-dataset additionalProperty, no invented fields)
  - Claim & Evidence: description as the editorial claim, sources as evidence
  - relationships (resolvable links only; category edges render as plain text)
  - main-site article link (only when the dataset record carries a url field)

Also writes the machine-readable retrieval index datasets/../site data:
  docs/entities/index.json  (all entity termCodes with type/url/relations)

Usage:
    python3 scripts/generate-entity-pages.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATASETS = ROOT / "datasets"
DOCS = ROOT / "docs"
ENTITIES_DIR = DOCS / "entities"
SITE_URL = "https://data.incenseherbs.com"

# Entity datasets that get per-entity pages. terminology keeps its anchor index.
ENTITY_DATASETS = ["ingredients", "aroma", "materials", "techniques", "forms", "comparisons"]
# Priority order for merging shared termCodes (ingredients carries the richest
# record: url + additionalProperty + sources). Others only fill gaps.
PRIORITY = ["ingredients", "comparisons", "materials", "forms", "techniques", "aroma"]

MANAGED_HEADER = (
    "<!-- AUTO-GENERATED by scripts/generate-entity-pages.py — "
    "projection of datasets/*.json. Do not edit by hand. -->\n\n"
)


def _prop(entity: dict, name: str, default: str = "") -> str:
    for p in entity.get("additionalProperty", []) or []:
        if p.get("name") == name:
            return str(p.get("value", default))
    return default


def _load(name: str) -> dict:
    with open(DATASETS / f"{name}.json", encoding="utf-8") as fh:
        return json.load(fh)


def _json_ld(entity: dict, code: str) -> str:
    """Entity-level JSON-LD. Only fields present in the dataset are emitted."""
    ld = {
        "@context": "https://schema.org",
        "@type": "DefinedTerm",
        "@id": f"{SITE_URL}/entities/{code}/#entity",
        "termCode": code,
        "name": entity.get("name"),
        "description": entity.get("description"),
        "url": f"{SITE_URL}/entities/{code}/",
    }
    if entity.get("alternateName"):
        ld["alternateName"] = entity["alternateName"]
    if entity.get("sameAs"):
        ld["sameAs"] = entity["sameAs"]
    if entity.get("url"):
        ld["mainEntityOfPage"] = {"@type": "WebPage", "@id": entity["url"]}
    if entity.get("additionalProperty"):
        ld["additionalProperty"] = entity["additionalProperty"]
    if entity.get("sources"):
        ld["citation"] = entity["sources"]
    ld = {k: v for k, v in ld.items() if v not in (None, "", [])}
    return "<script type=\"application/ld+json\">" + json.dumps(
        ld, ensure_ascii=False
    ) + "</script>"


def _md(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def render_entity_page(code: str, record: dict, rel_edges: list[dict]) -> str:
    name = record.get("name", code)
    zh = _prop(record, "Chinese")
    title = f"{name} ({zh})" if zh else name

    lines = [MANAGED_HEADER, f"# {title}\n", _json_ld(record, code), ""]

    # Claim & Evidence
    if record.get("description"):
        lines += [
            "## Claim & Evidence",
            "",
            f"**Claim:** {_md(record['description'])}",
            "",
        ]
        srcs = record.get("sources") or []
        if srcs:
            lines += [
                "**Evidence sources:**",
                "",
                "| Source | Type | Evidence level | Accessed |",
                "| --- | --- | --- | --- |",
            ]
            for s in srcs:
                title_s = _md(s.get("title", ""))
                s_type = _md(s.get("type", ""))
                level = _md(s.get("evidenceLevel", ""))
                url = s.get("url", "")
                accessed = s.get("accessed", "")
                label = f"[{title_s}]({url})" if url else title_s
                lines.append(f"| {label} | {s_type} | {level} | {accessed} |")
            lines.append("")

    # Attributes (per-dataset additionalProperty only)
    attrs = []
    for p in record.get("additionalProperty", []) or []:
        k = p.get("name")
        v = p.get("value")
        if k and v not in (None, ""):
            attrs.append((k, str(v)))
    if attrs:
        lines += ["## Attributes", "", "| Field | Value |", "| --- | --- |"]
        for k, v in attrs:
            lines.append(f"| {k} | {_md(v)} |")
        lines.append("")

    # Relationships — resolvable links only; category renders as plain text.
    if rel_edges:
        lines += ["## Relationships", "", "| Type | Related entity |", "| --- | --- |"]
        for e in rel_edges:
            rtype = e.get("type", "")
            rname = e.get("name", e.get("termCode", ""))
            rcode = e.get("termCode", "")
            if rtype == "category" or not rcode:
                lines.append(f"| {rtype} | {_md(rname)} |")
            else:
                lines.append(f"| {rtype} | [{_md(rname)}](/entities/{rcode}/) |")
        lines.append("")

    # Main site
    if record.get("url"):
        lines += [
            "## Main Site",
            "",
            f"Read the full article: [{name} on IncenseHerbs]({record['url']})",
            "",
        ]

    lines += [
        "---",
        "",
        "_Auto-generated from the LanDeng Open Datasets (single source of truth: "
        f"`datasets/*.json`). See [Format & Governance](/format/) for data "
        "conventions._",
        "",
    ]
    return "\n".join(lines)


def render_index_page(entities: dict[str, dict]) -> str:
    dataset = _load("ingredients")
    total = len(entities)
    lines = [
        MANAGED_HEADER,
        "# Entity Index",
        "",
        "One stable page per entity, generated from the entity datasets "
        "(ingredients, aroma, materials, techniques, forms, comparisons). Each "
        "page carries entity-level JSON-LD, attributes, relationships and "
        "evidence. The machine-readable retrieval index is "
        "[`entities/index.json`](/entities/index.json).",
        "",
        f"**Entities:** {total} · **Dataset dateModified:** {dataset.get('dateModified')}",
        "",
    ]
    grouped: dict[str, list[str]] = {}
    for c in sorted(entities):
        grouped.setdefault(c[0].upper(), []).append(c)
    for letter in sorted(grouped):
        lines.append(f"## {letter}")
        lines.append("")
        for c in grouped[letter]:
            lines.append(f"- [`{c}`](/entities/{c}/)")
        lines.append("")
    lines += [
        "---",
        "",
        "_Auto-generated — do not edit by hand._",
        "",
    ]
    return "\n".join(lines)


def build_retrieval_index(entities: dict[str, dict], rel_index: dict[str, list[dict]]) -> dict:
    """Machine-readable retrieval index: one compact record per entity."""
    out = []
    for code in sorted(entities):
        rec = entities[code]
        out.append({
            "termCode": code,
            "name": rec.get("name"),
            "datasets": rec["_datasets"],
            "url": f"{SITE_URL}/entities/{code}/",
            "mainSiteUrl": rec.get("url"),
            "relationCount": len(rel_index.get(code, [])),
        })
    return {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": "LanDeng entity retrieval index",
        "url": f"{SITE_URL}/entities/index.json",
        "numberOfItems": len(out),
        "itemListElement": out,
    }


def main() -> int:
    # 1) Merge entities across datasets; ingredients wins for shared termCodes.
    entities: dict[str, dict] = {}
    for stem in ENTITY_DATASETS:
        data = _load(stem)
        for e in data.get("mainEntity", []):
            code = e.get("termCode")
            if not code:
                continue
            if code not in entities:
                merged = dict(e)
                merged["_datasets"] = [stem]
                entities[code] = merged
            else:
                existing = entities[code]
                # Fill gaps from lower-priority records; never overwrite.
                for key, val in e.items():
                    if key in ("_datasets",):
                        continue
                    if val and not existing.get(key):
                        existing[key] = val
                if stem not in existing["_datasets"]:
                    existing["_datasets"].append(stem)

    # 2) Relationship edges per subject ingredient.
    relationships = _load("relationships")
    rel_index: dict[str, list[dict]] = {}
    for rec in relationships.get("mainEntity", []):
        rel_index[rec.get("termCode", "")] = rec.get("relatedEntity", []) or []

    # 3) Rebuild the managed directory from scratch (idempotent).
    ENTITIES_DIR.mkdir(parents=True, exist_ok=True)
    for stale in ENTITIES_DIR.glob("*.md"):
        if stale.name != "index.md":
            stale.unlink()

    for code, record in sorted(entities.items()):
        page = render_entity_page(code, record, rel_index.get(code, []))
        (ENTITIES_DIR / f"{code}.md").write_text(page, encoding="utf-8")

    # 4) Index page + retrieval index JSON.
    (ENTITIES_DIR / "index.md").write_text(render_index_page(entities), encoding="utf-8")
    idx = build_retrieval_index(entities, rel_index)
    (ENTITIES_DIR / "index.json").write_text(
        json.dumps(idx, ensure_ascii=False, indent=1) + "\n", encoding="utf-8"
    )

    print(f"OK: {len(entities)} entity pages + index + index.json written to docs/entities/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
